name: CI

on: [push]

jobs:
  basic:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        path: ./src/neilpa.me/go-x
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test ./...
